name: Docker Build and Push
# Run this Build for all pushes and PRs to 'main' and 'dev' branches.
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SHORT_SHA: $(echo ${{ github.sha }} | cut -c 1-8)

permissions:
  contents: read
jobs:
  test:
    env:
      # Node version to use, defaults to the current LTS version.
      node-version: "16.x"
      NODE_ENV: "test"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: Read environment variables
        run: cat {{ env.ENV_TEST }} > .env.test

      - name: run tests
        run: NODE_ENV=${{ env.NODE_ENV }} yarn test

  docker-build-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout codebase
        uses: actions/checkout@v3.3.0

      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/docker/login-action
      - name: Login to DockerHub
        # Only login if not a PR, as PRs only trigger a Docker build and not a push
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      ###############################################
      # Build/Push the API image
      ###############################################
      - name: Build, tag, and push image to Docker hub
        id: build-image
        run: |
          docker image build \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/web3-auction-api:latest \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/web3-auction-api:${{ env.SHORT_SHA }} \
          .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/web3-auction-api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/web3-auction-api:${{ env.SHORT_SHA }}
