name: Docker Build and Push
# Run this Build for all pushes and PRs to 'main' and 'dev' branches.
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SHORT_SHA: $(echo ${{ github.sha }} | cut -c 1-8)

permissions:
  contents: read
jobs:
  test:
    env:
      # Node version to use, defaults to the current LTS version.
      node-version: 18
      ENV_TEST: ${{ secrets.ENV_TEST }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Read environment variables
        run: |
          echo '
          ${{ env.ENV_TEST }}
          ' > .env.test

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test

  docker-build-push:
    needs: test
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
      DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_PASSWORD }}"
      IMAGE_NAME: web3-auction-api
    steps:
      # https://github.com/actions/checkout
      - name: Checkout codebase
        uses: actions/checkout@v4

      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      ###############################################
      # Build/Push the API image
      ###############################################
      - name: Build and tag image
        id: build-image
        run: |
          docker image build \
          --tag "${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest-${{ github.branch }}" \
          --tag ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}-${{ github.branch }} \
          .

      - name: Push image to image registry
        run: |
          docker push "${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest-${{ github.branch }}"
          docker push "${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}-${{ github.branch }}"
